### ISSUE TITLE
SImon simass : extreme seaice thickness in  HadGEM3-GC31- MM historical simulation.

### ISSUE THREAD

**Issue by martinjuckes** [cp4cds/cmip6_range_check_old#36]
Hi @matthew-mizielinski -- there is some extreme `simass`, up to 1,079,022 kg m-2, in the following file:

simass_SImon_HadGEM3-GC31-MM_historical_r1i1p1f3_gn_195001-196912.nc

This corresponds to roughly 1 km of ice, which is way over typical sea-ice thicknesses.

In the field where this occurs (time index 12) the top 10 values are:
1079022.375,   373581.0,
                        137635.71875,
                        19360.947265625,
                        20775.708984375,
                        19298.5390625,
                        22692.072265625,
                        18134.05859375,
                        18045.474609375,
                        17616.9140625

It looks as though there is one extreme point, with a few other very high values. Something similar also occurs in at least one other time step (maximum 1022628 kg m-2 and time step 228).

This value is also extreme relative to the other CMIP6 models. There is one model that gets up to 100,000 kg m-2 and several over 30,000 kg m-2, but most have a maximum below 10,000 kg m-2.

**Comment by matthew-mizielinski** [comment]
Thanks @martinjuckes, I can confirm that I see the same thing. A quick look at the file you've pointed at gives the following information for the top three time index 12, i.e. Jan 1951:

| row | column | value | latitude | longitude |
| ---- | ------- | ------ | ------| ------ |
| 348 | 914 | 1079022.4 | -63.89 | -58.5 |
| 1168 | 1136 | 373581.0 | 80.63 | 47.95 |
| 1180  | 1136  | 137635.72 | 81.12 | 56.04 |

In each case the sea-ice mass and thickness (sithick) fields show isolated grid points, with a time-series (within this file for 1950-1970 at least) showing a smooth evolution, i.e. this is not an isolated spike in time.

I'll pass this on to our sea-ice modellers for comment and hopefully some scoping of the issue, after which I'll look to issue an errata. 

Does your analysis cover UKESM1-0-LL or HadGEM3-GC31-LL?

**Comment by martinjuckes** [comment]
Thanks @matthew-mizielinski .

- UKESM1-0-LL has a maximum of 26,294 kg m-2, 
- HadGEM3-GC31-LL has a maximum of 21,900 kg m-2.

These values are higher than I would expect .. but not outliers in CMIP6.

**Comment by martinjuckes** [comment]
No surprise that the issue is visible in the thickness (`SImon.sithick`) as well, with maximum 1178m.

**Comment by martinjuckes** [comment]
@matthew-mizielinski : have you reached a conclusion on this 1km thick sea-ice yet?

**Comment by matthew-mizielinski** [comment]
Hi @martinjuckes , thanks for the poke.

I spoke with our sea ice group before Christmas and they believe that this is an artefact related to some of the mismatches between  the C-grid used by the NEMO ocean and the B-grid used by the CICE sea-ice model. For the LL  resolution models I think the sea mask was used to suppress these points, but this may have been missed from HadGEM3-GC31-MM.

I have issuing an errata for this on my todo list; we'll likely set this up as a "wont-fix" errata, with instructions on how to mask out the offending points

**Comment by matthew-mizielinski** [comment]
Hi @martinjuckes,

I've finally got the errata up for this. The issue with these grid points affects all HadGEM3-GC31-MM data. I've currently got this as a wont-fix errata as correcting this within our systems would be rather awkward to implement. This isn't ideal, but the effort involved in correcting this means that this isn't a high priority for us at this time.

Jon Seddon has also looked into this for the HighResMIP models and there are similar issues in some of their datasets.

Errata: https://errata.es-doc.org/static/view.html?uid=a6ccf92b-4fcf-bd5b-82db-65b227473569

**Comment by martinjuckes** [comment]
@matthew-mizielinski : thanks. We will pass the data on to C3S with a comment in the documentation.
